micronaut:
  server:
    http-version: 2.0
    ssl:
      enabled: true
      key-store:
        path: classpath:server.p12
        password: password
        type: PKCS12
    netty:
      listeners:
        http1:
          port: 8080
          ssl: false
        https:
          port: 8443
          ssl: true
      event-loops:
        default:
          num-threads: 4 # must match compute instance config
          prefer-native-transport: true