micronaut:
  server:
    http-version: 2.0
    date-header: false
    idle-timeout: 5m
    ssl:
      enabled: true
      ciphers: [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_AES_128_GCM_SHA256]
      build-self-signed: true
      handshake-timeout: 1m
    netty:
      listeners:
        http1:
          port: 8080
          ssl: false
        https:
          port: 8443
          ssl: true
      parent:
        event-loop-group: default
  netty:
    event-loops:
      default:
        num-threads: 3 # must match compute instance config
        prefer-native-transport: true