[oci.client.retry]
foo="bar"

[ssh]
# DO NOT use a valuable key here. It is uploaded to the hyperfoil controller for agent provisioning. If you don't need
# this for debugging, simply leave this property unset, and a fresh generated key pair will be used.
#private-key-location="/home/yawkat/.ssh/id_rsa"

[suite]
# independent repetitions of each benchmark
repetitions=1
max-concurrent-runs=25 # only respected for infrastructure-per-run
infrastructure-mode="reuse"

# the compartments to run the benchmark suite in. the compartment should be empty; it will be cleared before and after each run.
[[suite.location]]
compartment-id="ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
region="ap-tokyo-1"
availability-domain="hkYI:AP-TOKYO-1-AD-1"
[[suite.location]]
compartment-id="ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
region="ap-osaka-1"
availability-domain="hkYI:AP-OSAKA-1-AD-1"
[[suite.location]]
compartment-id="ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
region="ap-sydney-1"
availability-domain="hkYI:AP-SYDNEY-1-AD-1"
[[suite.location]]
compartment-id="ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
region="ap-melbourne-1"
availability-domain="hkYI:AP-MELBOURNE-1-AD-1"

# protocols to test
[load.protocols.http1]
protocol="HTTP1"
compile-ops=1000
shared-connections=16000
pipelining-limit=1
sla={"0.99"="200ms"}

[load.protocols.https1]
protocol="HTTPS1"
compile-ops=1000
shared-connections=20000
pipelining-limit=1
sla={"0.99"="200ms"}

[load.protocols.https2]
protocol="HTTPS2"
compile-ops=25
shared-connections=265
max-http2-streams=100
sla={"0.99"="200ms"}

# configuration for the hyperfoil cluster
[hyperfoil]
location="/home/yawkat/bin/hyperfoil-0.27"
agent-count=2

warmup-duration="1m"
pgo-duration="2m"
session-limit-factor=2
# duration per ops/s benchmark
benchmark-duration="2m"
agent-async-profiler=false

[perf-stat]
enabled=false
interval="5s"

[meminfo]
enabled=false
interval="5s"

[compute]
debug-authorized-keys=["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIObBGYqEuujvGhBwr1S/y+ungP2B7wFDmaX61Jek+Dli yawkat@yawkat-oracle"]

# configuration for the different compute instances for the benchmark

# core limits in my AD:
# VM.Standard.A1: 80 cores
# VM.Standard.E3.Flex: 150 cores
# VM.Standard.E4.Flex: 150 cores

# instance that the test server runs on
[compute.instance-types.benchmark-server]
shape="VM.Standard.E4.Flex"
ocpus=3
memory-in-gb=24
image="Oracle-Linux-9.5-2025.05.19-0"

# relay server used as an SSH gateway to other servers
[compute.instance-types.relay-server]
shape="VM.Standard.A1.Flex"
ocpus=1
memory-in-gb=2
image="Oracle-Linux-9.5-aarch64-2025.05.19-0"

# hyperfoil controller
[compute.instance-types.hyperfoil-controller]
shape="VM.Standard.A1.Flex"
ocpus=2
memory-in-gb=4
image="Oracle-Linux-9.5-aarch64-2025.05.19-0"

# hyperfoil agent
[compute.instance-types.hyperfoil-agent]
shape="VM.Standard.E5.Flex"
ocpus=8
memory-in-gb=16
image="Oracle-Linux-9.5-2025.05.19-0"

# nginx backend
[compute.instance-types.nginx]
shape="VM.Standard.E5.Flex"
ocpus=8
memory-in-gb=16
image="Oracle-Linux-9.5-2025.05.19-0"

# postgres backend
[compute.instance-types.postgresql]
shape="PostgreSQL.VM.Standard.E5.Flex"
ocpus=4
memory-in-gb=32
image=""

[variants.hotspot]
version=24
common-options="-XX:+UseZGC -Xms12G -Xmx12G -Dio.netty.iouring.iosqeAsyncThreshold=2147483647 -Dio.netty.iouring.ringSize=8192" # -Djdk.trackAllThreads=false -XX:+UnlockExperimentalVMOptions -XX:-DoJVMTIVirtualThreadTransitions
option-choices=[""]

[variants.hotspot.async-profiler]
enabled=false
args="start,event=cpu,cstack=vm,file=profile.jfr"
jfr-config="jdk.ObjectAllocationSample#enabled=false jdk.OldObjectSample#enabled=false"
outputs=["profile.jfr"]

[[variants.hotspot.async-profiler.conversion]]
input="profile.jfr"
output="flamegraph.html"
args="--output html"
[[variants.hotspot.async-profiler.conversion]]
input="profile.jfr"
output="heatmap.html"
args="--output heatmap"

[variants.native-image]
version=23
# these are native-image options that are benchmarked against each other
option-choices=["--gc=G1"]
# these are framework-specific options that are just required to get the build to work :)
prefix-options.mn="-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jni=ALL-UNNAMED -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED"

# micronaut variant configuration
[variants.micronaut.compile-variants]
tcnative=[
    "on",
    #"off"
]
transport=[
    #"nio",
    #"epoll",
    "iouring"
]
json=[
    "jackson",
    #"serde"
]
micronaut=[
    "latest",
]
loom=[
    "off",
    "on",
    "carried"
]
affinity=[
    #"off",
    #"preferred",
    "enforced",
    #"jdkclient"
]

[techempower]
compartment-id="ocid1.compartment.oc1..aaaaaaaaxhkap5z4hpt3zbbxrxmohfd3nkaf7bxh2p6f6ufalbtaxupgyj2q"
region="ap-tokyo-1"
availability-domain="hkYI:AP-TOKYO-1-AD-1"

[compute.instance-types.te-server]
shape="BM.Standard3.64"
ocpus=64
memory-in-gb=1024
image="Oracle-Linux-9.5-2025.05.19-0"
[compute.instance-types.te-client]
shape="VM.Standard.E4.Flex"
ocpus=64
memory-in-gb=64
image="Oracle-Linux-9.5-2025.05.19-0"
[compute.instance-types.te-database]
shape="VM.Standard.E4.Flex"
ocpus=64
memory-in-gb=256
image="Oracle-Linux-9.5-2025.05.19-0"
[compute.instance-types.te-toolset]
shape="VM.Standard.E4.Flex"
ocpus=2
memory-in-gb=4
image="Oracle-Linux-9.5-2025.05.19-0"
