[oci.client.retry]
foo="bar"

[oci.clients.objectstorage]
read-timeout = "5m"

[ssh]
# DO NOT use a valuable key here. It is uploaded to the hyperfoil controller for agent provisioning. If you don't need
# this for debugging, simply leave this property unset, and a fresh generated key pair will be used.
#private-key-location="/home/yawkat/.ssh/id_rsa"

[suite]
name="standard"

# The benchmark compartment should be empty; it is cleared before and after the suite.
[suite.location]
compartment-id="ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
region="eu-frankfurt-1"
availability-domain="hkYI:EU-FRANKFURT-1-AD-1"

[tcp-agent-relay]
bucket-namespace="oraclelabs"
bucket-name="benchmark-data-bucket"

[console-history]
poll-interval="10s"
capture-timeout="60s"
state-poll-interval="1s"
max-bytes="1MB"
max-concurrent-captures=4

# configuration for the hyperfoil cluster
[hyperfoil]
agent-count=2

[perf-stat]
enabled=false
interval="5s"

[meminfo]
enabled=false
interval="5s"

[compute]
debug-authorized-keys=["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIObBGYqEuujvGhBwr1S/y+ungP2B7wFDmaX61Jek+Dli yawkat@yawkat-oracle"]
storage-bucket-compartment = "ocid1.compartment.oc1..aaaaaaaaqpsmu5vcjf75ejqwvhhg75ndjpjdmxihi2gltvb5zazhv2oe7wea"
storage-bucket-namespace = "oraclelabs"
storage-bucket-name = "benchmark-storage"

[variants.hotspot]
version=24
common-options="-XX:+UseZGC -Xms12G -Xmx12G -Dio.netty.iouring.iosqeAsyncThreshold=2147483647 -Dio.netty.iouring.ringSize=8192"
option-choices={ ""="" }
