[techempower]
repetitions=3
tests=["micronaut", "micronaut-loom-fjp", "micronaut-loom-on-netty", "micronaut-jdbc", "micronaut-jdbc-loom-fjp", "micronaut-jdbc-loom-on-netty"]
types=["plaintext", "db"]
duration="60s"

[[techempower.revision]]
github-repo-name="yawkat/TE-FrameworkBenchmarks"
ref="loom-benchmarks-jdbc"

[variants.hotspot.async-profiler]
enabled=true
args="start,event=cpu,cstack=vm"

[compute.instance-types.te-server]
shape="VM.Standard.E4.Flex"
ocpus=8
memory-in-gb=64
image="Oracle-Linux-[\\d\\.]+-202.+"
disk-performance-units=80
[compute.instance-types.te-client]
shape="VM.Standard.E4.Flex"
ocpus=16
memory-in-gb=32
image="Oracle-Linux-[\\d\\.]+-202.+"
disk-performance-units=80
[compute.instance-types.te-database]
shape="VM.Standard.E4.Flex"
ocpus=16
memory-in-gb=32
image="Oracle-Linux-[\\d\\.]+-202.+"
disk-performance-units=80
[compute.instance-types.te-toolset]
shape="VM.Standard.E4.Flex"
ocpus=2
memory-in-gb=4
image="Oracle-Linux-[\\d\\.]+-202.+"
disk-performance-units=80
