[[load.documents]]
name="loop"
method="GET"
uri="/loop"
response-body='Hello World'
response-matching-mode='EQUAL'

[[hyperfoil.status]]
name="status"
uri="/status"

[suite]
enabled-run-types=[
    "mn-hotspot",
]

[variants.hotspot]
common-options="-XX:+UseZGC -Xms12G -Xmx12G -Dio.netty.iouring.iosqeAsyncThreshold=2147483647 -Dio.netty.iouring.ringSize=8192 -Dmicronaut.environments=loom,affinity --add-opens=java.base/java.lang=ALL-UNNAMED -Djdk.trackAllThreads=false -XX:+UnlockExperimentalVMOptions -XX:-DoJVMTIVirtualThreadTransitions"

[load.protocols.http1]
enabled=true
ops=[2000, 8000, 16000, 32000, 48000, 64000, 96000, 128000, 160000, 192000, 256000]

[load.protocols.https1]
#enabled=true
ops=[1000, 4000, 8000, 16000, 24000, 32000, 48000, 64000, 80000]

[variants.hotspot.async-profiler]
enabled=true
