quarkus.http.port=8080
quarkus.http.ssl-port=8443
quarkus.http.http2=true
quarkus.http.insecure-requests=enabled
quarkus.http.ssl.certificate.key-store-file=keys.p12
quarkus.http.ssl.certificate.key-store-password=password
quarkus.http.ssl.certificate.key-store-file-type=PKCS12
quarkus.http.ssl.cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_AES_128_GCM_SHA256
quarkus.vertx.prefer-native-transport=true
benchmark.systemd-readiness.enabled=false
