[libraries]
hyperfoil-api = { group = "io.hyperfoil", name = "hyperfoil-api", version.ref = "hyperfoil" }
hyperfoil-core = { group = "io.hyperfoil", name = "hyperfoil-core", version.ref = "hyperfoil" }
hyperfoil-clustering = { group = "io.hyperfoil", name = "hyperfoil-clustering", version.ref = "hyperfoil" }
async-profiler-jfr-converter = { group = "tools.profiler", name = "jfr-converter", version.ref = "async-profiler" }
openjdk-jmc-flightrecorder-writer = { group = "org.openjdk.jmc", name = "flightrecorder.writer", version.ref = "openjdk-jmc" }
mina-sshd-core = { group = "org.apache.sshd", name = "sshd-core", version.ref = "mina-sshd" }
mina-sshd-scp = { group = "org.apache.sshd", name = "sshd-scp", version.ref = "mina-sshd" }
mina-sshd-sftp = { group = "org.apache.sshd", name = "sshd-sftp", version.ref = "mina-sshd" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
bcpkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
agroal = { group = "io.agroal", name = "agroal-pool", version.ref = "agroal" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
chartjs = { group = "software.xdev", name = "chartjs-java-model", version.ref = "chartjs" }
svm = { group = "org.graalvm.nativeimage", name = "svm", version.ref = "svm" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-codec-http = { group = "io.netty", name = "netty-codec-http", version.ref = "netty" }
netty-codec-http2 = { group = "io.netty", name = "netty-codec-http2", version.ref = "netty" }
netty-pkitesting = { group = "io.netty", name = "netty-pkitesting", version.ref = "netty" }
netty-io-uring = { group = "io.netty", name = "netty-transport-native-io_uring", version.ref = "netty" }
jackson-databind = { group = "tools.jackson.core", name = "jackson-databind", version.ref = "jackson" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testcontainers" }
helidon-webserver = { group = "io.helidon.webserver", name = "helidon-webserver", version.ref = "helidon" }
helidon-webserver-http2 = { group = "io.helidon.webserver", name = "helidon-webserver-http2", version.ref = "helidon" }
helidon-http-media-jsonb = { group = "io.helidon.http.media", name = "helidon-http-media-jsonb", version.ref = "helidon" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-jetty = { group = "org.springframework.boot", name = "spring-boot-starter-jetty", version.ref = "spring-boot" }
jetty-alpn-server = { group = "org.eclipse.jetty", name = "jetty-alpn-server", version.ref = "jetty" }
jetty-alpn-java-server = { group = "org.eclipse.jetty", name = "jetty-alpn-java-server", version.ref = "jetty" }
jetty-http2-server = { group = "org.eclipse.jetty.http2", name = "jetty-http2-server", version.ref = "jetty" }
vertx-web = { group = "io.vertx", name = "vertx-web", version.ref = "vertx" }
vertx-io-uring-incubator = { group = "io.vertx", name = "vertx-io_uring-incubator", version.ref = "vertx" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "8.3.11" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[versions]
hyperfoil = "0.29.3"
async-profiler = "4.5"
openjdk-jmc = "9.1.2"
mina-sshd = "2.19.0"
micronaut = "5.1.0"
micronaut-gradle = "5.0.2"
netty = "4.2.16.Final"
jackson = "3.2.1"
bouncycastle = "1.85"
logback = "1.5.19"
hikari = "6.3.3"
agroal = "2.8.2"
postgresql = "42.7.13"
chartjs = "2.9.1"
svm = "25.0.4"
junit5 = "5.14.4"
testcontainers = "2.0.5"
helidon = "4.5.1"
spring-boot = "3.5.16"
jetty = "12.0.36"
vertx = "4.5.31"
slf4j = "2.0.17"
