micronaut:
  server:
    http-version: 2.0
    date-header: false
    idle-timeout: 5m
    ssl:
      enabled: true
      port: 8443
      key-name: benchmark
      key:
        password: password
      ciphers: [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_AES_128_GCM_SHA256]
      handshake-timeout: 1m
    dual-protocol: true
    netty:
      parent:
        event-loop-group: default
  http:
    client:
      event-loop-group: default
      pool:
        connection-locality: ignore
        max-concurrent-http1-connections: 300
  netty:
    event-loops:
      default:
        transport: [io_uring]
  certificate:
    resource:
      benchmark:
        resource: classpath:server.p12
        password: password
        format: PKCS12

loop-remote: http://10.0.0.10
